<table>
    <thead>
    <tr>
        <th>Name</th>
        <th>Email</th>
    </tr>
    </thead>
    <tbody>
        <tr>
            <td>Guilherme</td>
            <td>GG</td>
        </tr>
    </tbody>
</table>